<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Database\Chaussure;
use Illuminate\Support\Facades\DB;

class ChaussuresTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $chaussures = [

                        [
                           'modele' => 'Air Max 90',
                           'marque' => 'Nike',
                           'genre' => 'Homme',
                           'couleurP' => 'Blanc',
                           'couleurS' => 'Blanc',
                           'prix' => 110.00,
                           'created_at' => now(),
                           'updated_at' => now(),
                       ],

                       [
                           'modele' => 'AIR MAX 97',
                           'marque' => 'Nike',
                           'genre' => 'Homme',
                           'couleurP' => 'Noir',
                           'couleurS' => 'Rouge',
                           'prix' => 99.99,
                           'created_at' => now(),
                           'updated_at' => now(),
                       ],
                       [
                           'modele' => 'AIR MAX ESSENTIAL 95',
                           'marque' => 'nike',
                           'genre' => 'Homme',
                           'couleurP' => 'noir',
                           'couleurS' => 'noir',
                           'prix' => 95.99,
                           'created_at' => now(),
                           'updated_at' => now(),
                       ],
                         [
                           'modele' => 'CLASSIC XXI',
                           'marque' => 'puma',
                           'genre' => 'Homme',
                           'couleurP' => 'vert',
                           'couleurS' => 'blanc',
                           'prix' => 70.99,
                           'created_at' => now(),
                           'updated_at' => now(),
                       ],
                     [
                           'modele' => 'CLASSIC XXI',
                           'marque' => 'puma',
                           'genre' => 'Homme',
                           'couleurP' => 'rouge',
                           'couleurS' => 'blanc',
                           'prix' => 70.99,
                           'created_at' => now(),
                           'updated_at' => now(),
                       ],
                     [
                           'modele' => 'SLIPSTREAM ARCHIVE',
                           'marque' => 'puma',
                           'genre' => 'Homme',
                           'couleurP' => 'vert',
                           'couleurS' => 'blanc',
                           'prix' => 85.99,
                           'created_at' => now(),
                           'updated_at' => now(),
                       ],
                        [
                           'modele' => '2002',
                           'marque' => 'NewBalance',
                           'genre' => 'femme',
                           'couleurP' => 'beige',
                           'couleurS' => 'blanc',
                           'prix' => 150.99,
                           'created_at' => now(),
                           'updated_at' => now(),
                       ],
                        [
                           'modele' => '2002',
                           'marque' => 'NewBalance',
                           'genre' => 'homme',
                           'couleurP' => 'noir',
                           'couleurS' => 'blanc',
                           'prix' => 150.99,
                           'created_at' => now(),
                           'updated_at' => now(),
                       ],
                         [
                           'modele' => 'MS327',
                           'marque' => 'NewBalance',
                           'genre' => 'homme',
                           'couleurP' => 'noir',
                           'couleurS' => 'blanc',
                           'prix' => 150.99,
                           'created_at' => now(),
                           'updated_at' => now(),
                       ],
                         [
                           'modele' => 'CAMPUS 00S',
                           'marque' => 'Adidas',
                           'genre' => 'femme',
                           'couleurP' => 'Gris',
                           'couleurS' => 'Blanc',
                           'prix' => 70.99,
                           'created_at' => now(),
                           'updated_at' => now(),
                       ],
                        [
                           'modele' => 'CAMPUS 00S',
                           'marque' => 'Adidas',
                           'genre' => 'femme',
                           'couleurP' => 'Orenge',
                           'couleurS' => 'Blanc',
                           'prix' => 70.99,
                           'created_at' => now(),
                           'updated_at' => now(),
                       ],
                         [
                           'modele' => 'CAMPUS 00S',
                           'marque' => 'Adidas',
                           'genre' => 'Homme',
                           'couleurP' => 'vert',
                           'couleurS' => 'Blanc',
                           'prix' => 70.99,
                           'created_at' => now(),
                           'updated_at' => now(),
                       ],
                //          [
                //            'modele' => 'FORUM MID',
                //            'marque' => 'Adidas',
                //            'genre' => 'Homme',
                //            'couleurP' => 'noir',
                //            'couleurS' => 'Noir',
                //            'prix' => 110.99,
                //          'image' => 'FORUM MID black',
                //            'created_at' => now(),
                //            'updated_at' => now(),
                //        ],
                //         [
                //            'modele' => 'FORUM MID',
                //            'marque' => 'Adidas',
                //            'genre' => 'Homme',
                //            'couleurP' => 'Blanc',
                //            'couleurS' => 'Blanc',
                //            'prix' => 110.99,
                //         'image' => 'FORUM MID white',
                //            'created_at' => now(),
                //            'updated_at' => now(),
                //        ],
                //         [
                //            'modele' => 'Chunky',
                //            'marque' => 'Bershka',
                //            'genre' => 'Homme',
                //            'couleurP' => 'noir',
                //            'couleurS' => 'noir',
                //            'prix' => 55.99,
                //    'image' => 'CHUNKY black1',
                //            'created_at' => now(),
                //            'updated_at' => now(),
                //        ],

                //        [
                //            'modele' => 'BLAZER MID 77',
                //            'marque' => 'Nike',
                //            'genre' => 'Homme',
                //            'couleurP' => 'Blanc',
                //            'couleurS' => 'Noir',
                //            'prix' => 140.99,
                //             'image' => 'BLAZER MID 77 WHITE BLACK',
                //            'created_at' => now(),
                //            'updated_at' => now(),
                //        ],
                //        [
                //            'modele' => 'BLAZER MID 77',
                //            'marque' => 'Nike',
                //            'genre' => 'Homme',
                //            'couleurP' => 'Blanc',
                //            'couleurS' => 'bleu',
                //            'prix' => 140.99,
                //    'image' => 'BLAZER MID 77 WHITE BLEU',
                //            'created_at' => now(),
                //            'updated_at' => now(),
                //        ],
                //        [
                //            'modele' => 'JUMPMAN TWO TREY',
                //            'marque' => 'Nike',
                //            'genre' => 'Homme',
                //            'couleurP' => 'Blanc',
                //            'couleurS' => 'bleu',
                //            'prix' => 160.99,
                //    'image' => 'JUMPMAN TWO TREY white blue',
                //            'created_at' => now(),
                //            'updated_at' => now(),
                //        ],
                //        [
                //            'modele' => 'NIKE DUNK HI ',
                //            'marque' => 'Nike',
                //            'genre' => 'Homme',
                //            'couleurP' => 'Blanc',
                //            'couleurS' => 'bleu',
                //            'prix' => 160.99,
                //    'image' => 'NIKE DUNK HI white blue',
                //            'created_at' => now(),
                //            'updated_at' => now(),
                //        ],
                //        [
                //            'modele' => 'NIKE DUNK HI ',
                //            'marque' => 'Nike',
                //            'genre' => 'Homme',
                //            'couleurP' => 'Blanc',
                //            'couleurS' => 'Rouge',
                //            'prix' => 160.99,
                //    'image' => 'NIKE DUNK HI white rouge',
                //            'created_at' => now(),
                //            'updated_at' => now(),
                //        ],
                //        [
                //            'modele' => 'UA SK8-HI',
                //            'marque' => 'Vans',
                //            'genre' => 'Homme',
                //            'couleurP' => 'Noir',
                //            'couleurS' => 'Noir',
                //            'prix' => 70.99,
                //    'image' => 'UA SK8-HI BLACK',
                //            'created_at' => now(),
                //            'updated_at' => now(),
                //        ],
                //        [
                //            'modele' => 'UA SK8-HI',
                //            'marque' => 'Vans',
                //            'genre' => 'Homme',
                //            'couleurP' => 'Blanc',
                //            'couleurS' => 'Blanc',
                //            'prix' => 70.99,
                //    'image' => 'UA SK8-HI WHITE',
                //            'created_at' => now(),
                //            'updated_at' => now(),
                //        ],
                //        [
                //            'modele' => '550',
                //            'marque' => 'NewBalanc',
                //            'genre' => 'Homme',
                //            'couleurP' => 'noir',
                //            'couleurS' => 'Grise',
                //            'prix' => 99.99,
                //    'image' => '550 GRISE',
                //            'created_at' => now(),
                //            'updated_at' => now(),
                //        ],
                //        [
                //            'modele' => '550',
                //            'marque' => 'NewBalanc',
                //            'genre' => 'Homme',
                //            'couleurP' => 'Blanc',
                //            'couleurS' => 'bleu',
                //            'prix' => 99.99,
                //    'image' => '550 WHITE BLEU',
                //            'created_at' => now(),
                //            'updated_at' => now(),
                //        ],
                //        [
                //            'modele' => '550',
                //            'marque' => 'NewBalanc',
                //            'genre' => 'Homme',
                //            'couleurP' => 'Blanc',
                //            'couleurS' => 'Blanc',
                //            'prix' => 99.99,
                //    'image' => '550 WHITE',
                //            'created_at' => now(),
                //            'updated_at' => now(),
                //        ],

                //        [
                //            'modele' => 'ADI2000',
                //            'marque' => 'Adidas',
                //            'genre' => 'Homme',
                //            'couleurP' => 'Blanc',
                //            'couleurS' => 'Bleu',
                //            'prix' => 84.99,
                //    'image' => 'ADI2000 white bleu',
                //            'created_at' => now(),
                //            'updated_at' => now(),
                //        ],
                //        [
                //            'modele' => 'ADI2000',
                //            'marque' => 'Adidas',
                //            'genre' => 'femme',
                //            'couleurP' => 'Blanc',
                //            'couleurS' => 'orange',
                //            'prix' => 84.99,
                //    'image' => 'ADI2000 white orange',
                //            'created_at' => now(),
                //            'updated_at' => now(),
                //        ],

        ];

        foreach ($chaussures as $chaussure) {
            DB::table('chaussures')->insert($chaussure);
        }
    }
}
